### PR TITLE
Add logs in logstash format

### PR DESCRIPTION
**Pull request by apsavin**
For review @jifeon @AGresvig

### CODE REVIEW

**Comment by apsavin** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;kMQUNXC6&#x2F;472-gui-for-viewing-filtering-logs"> GUI for viewing &amp; filtering logs</a>

**Comment by AGresvig** [comment]
LGTM!

**Comment by jifeon** [comment]
Do we need update plyo.db and plyo.registration too? 

How will we use these logs, I thought we pipe docker output to ELK, but docker output it goes through `Console` adapter, not `File`.

**Comment by apsavin** [comment]
> Do we need to update plyo.db and plyo.registration too? 

We do not need to update plyo.db: we don't have a separate logger there during work of our applications.
We do need update plyo.registration, but I want to set up one project (plyo.web) first.

> How will we use these logs

We will use [filebeat](https://www.elastic.co/products/beats/filebeat), it will read logs from file and send to logstash. Logs will be in a VOLUME, filebeat in a separate docker container.

**Pull request merged**
